languaje: node_js
node_js:
  - stable
branches:
  - develop
  - master
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  api_key: $HEROKU
  app: time-trade-backend
  on:
    branch: master
